GSP = GSP or {}

GSP.Languages = {
    pl = "Polski (PL)",
    en = "English (EN)",
    fr = "Français (FR)",
    ru = "Русский (RU)",
    es = "Español (ES)", 
    de = "Deutsch (DE)"
}

GSP.DefaultLanguage = "en"
GSP.CurrentLanguage = "en" 

GSP.Translations = {
    pl = {
        player = {
            title_server = "GSP - Gmod Sound Player (Zarządzanie Serwerem)",
            title_client = "GSP - Gmod Sound Player (Zarządzanie Klientem)",
            close_panel = "✕ ZAMKNIJ PANEL",
            
            now_playing = "TERAZ ODTWARZANE",
            now_playing_glob = "TERAZ ODTWARZANE (GLOB)",
            now_playing_local = "TERAZ ODTWARZANE (LOKALNIE)",
            no_song = "Brak utworu",
            uploader_system = "SYSTEM",
            uploader_you = "TY",
            uploader_prefix = "Uploader",
            pending_count = "Oczekujących",
            pending_you = "Oczekujących u Ciebie",
            live = "NA ŻYWO",

            local_songs = "Lokalne utwory serwera",
            all_files = "Wszystkich plików",
            search_placeholder = "Szukaj utworu...",
            no_files = "Brak plików w sound/GSP/. Możesz wypróbować testowej paczki muzycznej będącej w opisie moda (GSP Template)",
            btn_play = "▶ ODTWÓRZ",
            btn_queue = "＋ KOLEJKA",

            tab_control = "KONTROLA",
            tab_queue = "KOLEJKA",
            tab_settings = "USTAWIENIA",

            dj_mode = "Tryb Serwera",
            dj_mode_desc_on = "Nadpisujesz stan całego serwera",
            dj_mode_desc_off = "Zarządzasz tylko swoim klientem",

            vol_global = "Głośność Globalna (Serwer)",
            vol_local = "Twoja Głośność (Klient)",
            btn_pause = "⏸ PAUZA",
            btn_resume = "▶ WZNÓW",
            btn_loop_server = "🔁 ZAPĘTL SERWER",
            btn_loop_client = "🔁 ZAPĘTL KLIENTA",
            btn_stop = "STOP",
            btn_next = "NASTĘPNY UTWÓR ⏩",
            url_player_title = "Zdalny odtwarzacz URL",
            url_player_placeholder = "Wklej link i kliknij Enter...",

            queue_pending_title = "Utwory oczekujące",
            queue_all = "(Dla wszystkich)",
            queue_you = "(Tylko dla Ciebie)",
            queue_empty = "Kolejka jest pusta.",
            queue_client_empty = "Twoja lokalna kolejka jest pusta.",
            queue_upcoming = "Nadchodzące utwory (Lokalne)",

            local_settings_title = "Ustawienia Lokalne (Twój Klient)",
            mute_title = "Całkowite wyciszenie",
            mute_desc = "Zatrzymuje dźwięk modyfikacji na Twoim komputerze.",
            lang_title = "Język interfejsu (Language)",
            lang_desc = "Wybierz język panelu / Choose player language.",

            personal_settings = "Ustawienia Osobiste",
            btn_mute = "🔇 WYCISZ CAŁKOWICIE (MUTE)",
            btn_unmute = "🔊 ODCISZ MUZYKĘ (UNMUTE)",
            btn_save_default_vol = "💾 ZAPISZ GŁOŚNOŚĆ JAKO DOMYŚLNĄ",

            footer_dual_engine = "GSP System: Dual Audio Engine",
            footer_client_mode = "GSP Client Mode",
            footer_admin_mode = "Admin / Server Mode",
            footer_local_mode = "Local Client Mode",

            close_key_title = "Klawisz zamknięcia panelu",                     
            close_key_desc = "Wybierz klawisz szybkiego zamykania interfejsu.",  
            press_any_key = "NACIŚNIJ KLAWISZ.",                             
        },
        admin = {
            title = "GSP - PANEL ADMINISTRATORA UPRAWNIEŃ",
            close_panel = "✕ ZAMKNIJ PANEL",

            music_ranks_title = "RANGI MUZYCZNE (DJ)",
            music_ranks_desc = "Użytkownicy z tymi rangami mają dostęp do odtwarzacza !music oraz DJ-skich funkcji serwerowych.",

            admin_ranks_title = "RANGI ADMINISTRACYJNE (MGR)",
            admin_ranks_desc = "Użytkownicy z tymi rangami mają pełen dostęp do tego panelu i decydują o tym, kto jest DJ-em oraz Administratorem rang.",

            input_placeholder = "Nazwa rangi...",
            btn_add = "DODAJ",
            rank_protected = "Zabezpieczona",
            tool_delete = "Usuń rangę",

            footer_engine = "GSP Permissions Engine: Standalone Management Window",
            footer_area = "Admin Security Area"
        }
    },
    en = {
        player = {
            title_server = "GSP - Gmod Sound Player (Server Control)",
            title_client = "GSP - Gmod Sound Player (Client Control)",
            close_panel = "✕ CLOSE PANEL",

            now_playing = "NOW PLAYING",
            now_playing_glob = "NOW PLAYING (GLOB)",
            now_playing_local = "NOW PLAYING (LOCAL)",
            no_song = "No song",
            uploader_system = "SYSTEM",
            uploader_you = "YOU",
            uploader_prefix = "Uploader",
            pending_count = "Pending",
            pending_you = "Pending for you",
            live = "LIVE",

            local_songs = "Local Server Songs",
            all_files = "All files",
            search_placeholder = "Search song...",
            no_files = "Files are missing from sound/GSP/. You can try the test music pack included in the mod's description (GSP Template).",
            btn_play = "▶ PLAY",
            btn_queue = "＋ QUEUE",

            tab_control = "CONTROL",
            tab_queue = "QUEUE",
            tab_settings = "SETTINGS",

            dj_mode = "Server Mode",
            dj_mode_desc_on = "Overriding global server state",
            dj_mode_desc_off = "Managing your local client only",

            vol_global = "Global Volume (Server)",
            vol_local = "Your Volume (Client)",
            btn_pause = "⏸ PAUSE",
            btn_resume = "▶ RESUME",
            btn_loop_server = "🔁 LOOP SERVER",
            btn_loop_client = "🔁 LOOP CLIENT",
            btn_stop = "STOP",
            btn_next = "NEXT TRACK ⏩",
            url_player_title = "Remote URL Player",
            url_player_placeholder = "Paste link and press Enter...",

            queue_pending_title = "Pending tracks",
            queue_all = "(For everyone)",
            queue_you = "(Only for you)",
            queue_empty = "Queue is empty.",
            queue_client_empty = "Your local queue is empty.",
            queue_upcoming = "Upcoming tracks (Local)",

            local_settings_title = "Local Settings (Your Client)",
            mute_title = "Total Mute",
            mute_desc = "Completely mutes the addon sound on your computer.",
            lang_title = "Interface Language",
            lang_desc = "Choose interface language.",

            personal_settings = "Personal Settings",
            btn_mute = "🔇 MUTE ADDON",
            btn_unmute = "🔊 UNMUTE ADDON",
            btn_save_default_vol = "💾 SAVE VOLUME AS DEFAULT",

            footer_dual_engine = "GSP System: Dual Audio Engine",
            footer_client_mode = "GSP Client Mode",
            footer_admin_mode = "Admin / Server Mode",
            footer_local_mode = "Local Client Mode",
            
            close_key_title = "Panel Close Key",                                
            close_key_desc = "Choose shortcut key to close interface.",         
            press_any_key = "PRESS ANY KEY...",                              
        },
        admin = {
            title = "GSP - PERMISSIONS ADMIN PANEL",
            close_panel = "✕ CLOSE PANEL",

            music_ranks_title = "MUSIC RANKS (DJ)",
            music_ranks_desc = "Users with these ranks can access the !music player and global DJ server features.",

            admin_ranks_title = "ADMINISTRATIVE RANKS (MGR)",
            admin_ranks_desc = "Users with these ranks have full access to this panel and decide who is a DJ and who is a Permissions Admin.",

            input_placeholder = "Rank name...",
            btn_add = "ADD",
            rank_protected = "Protected",
            tool_delete = "Remove rank",

            footer_engine = "GSP Permissions Engine: Standalone Management Window",
            footer_area = "Admin Security Area"
        }
    },
    fr = {
        player = {
            title_server = "GSP - Gmod Sound Player (Contrôle Serveur)",
            title_client = "GSP - Gmod Sound Player (Contrôle Client)",
            close_panel = "✕ FERMER LE PANNEAU",
            now_playing = "EN LECTURE",
            now_playing_glob = "EN LECTURE (GLOBAL)",
            now_playing_local = "EN LECTURE (LOCAL)",
            no_song = "Aucun morceau",
            uploader_system = "SYSTÈME",
            uploader_you = "TOI",
            uploader_prefix = "Uploader",
            pending_count = "En attente",
            pending_you = "En attente pour toi",
            live = "EN DIRECT",
            local_songs = "Musiques Locales du Serveur",
            all_files = "Tous les fichiers",
            search_placeholder = "Rechercher une musique...",
            no_files = "Il manque des fichiers dans sound/GSP/. Vous pouvez essayer le pack de musique de test inclus dans la description du mod (GSP Template).",
            btn_play = "▶ LIRE",
            btn_queue = "＋ FILE",
            tab_control = "CONTRÔLE",
            tab_queue = "FILE",
            tab_settings = "PARAMÈTRES",
            dj_mode = "Mode Serveur",
            dj_mode_desc_on = "Écraser l'état global du serveur",
            dj_mode_desc_off = "Gérer uniquement votre client local",
            vol_global = "Volume Global (Serveur)",
            vol_local = "Votre Volume (Client)",
            btn_pause = "⏸ PAUSE",
            btn_resume = "▶ REPRENDRE",
            btn_loop_server = "🔁 BOUCLER SERVEUR",
            btn_loop_client = "🔁 BOUCLER CLIENT",
            btn_stop = "STOP",
            btn_next = "PISTE SUIVANTE ⏩",
            url_player_title = "Lecteur URL à distance",
            url_player_placeholder = "Collez le lien et appuyez sur Entrée...",
            queue_pending_title = "Pistes en attente",
            queue_all = "(Pour tout le monde)",
            queue_you = "(Uniquement pour toi)",
            queue_empty = "La file d'attente est vide.",
            queue_client_empty = "Votre file d'attente locale est vide.",
            queue_upcoming = "Pistes à venir (Local)",
            local_settings_title = "Paramètres Locaux (Votre Client)",
            mute_title = "Sourdine Totale",
            mute_desc = "Coupe complètement le son de l'addon sur votre ordinateur.",
            lang_title = "Langue de l'interface",
            lang_desc = "Choisissez la langue de l'interface.",
            personal_settings = "Paramètres Personnels",
            btn_mute = "🔇 COUPER L'ADDON",
            btn_unmute = "🔊 RÉACTIVER LE SON",
            btn_save_default_vol = "💾 ENREGISTRER LE VOLUME PAR DÉFAUT",
            footer_dual_engine = "GSP Système: Dual Audio Engine",
            footer_client_mode = "GSP Mode Client",
            footer_admin_mode = "Mode Admin / Serveur",
            footer_local_mode = "Mode Client Local",
            close_key_title = "Touche de fermeture du panneau",
            close_key_desc = "Choisissez la touche de raccourci pour fermer l'interface.",
            press_any_key = "APPUYEZ SUR UNE TOUCHE...",
        },
        admin = {
            title = "GSP - PANNEAU D'ADMINISTRATION DES PERMISSIONS",
            close_panel = "✕ FERMER LE PANNEAU",
            music_ranks_title = "GRADES MUSIQUE (DJ)",
            music_ranks_desc = "Les utilisateurs avec ces grades peuvent accéder au lecteur !music et aux fonctionnalités globales du serveur DJ.",
            admin_ranks_title = "GRADES ADMINISTRATIFS (MGR)",
            admin_ranks_desc = "Les utilisateurs avec ces grades ont un accès complet à ce panneau et décident qui est DJ et qui est Administrateur des permissions.",
            input_placeholder = "Nom du grade...",
            btn_add = "AJOUTER",
            rank_protected = "Protégé",
            tool_delete = "Supprimer le grade",
            footer_engine = "GSP Moteur de Permissions: Fenêtre de gestion autonome",
            footer_area = "Zone de sécurité administrative"
        }
    },
    ru = {
        player = {
            title_server = "GSP - Gmod Sound Player (Управление Сервером)",
            title_client = "GSP - Gmod Sound Player (Управление Клиентом)",
            close_panel = "✕ ЗАКРЫТЬ ПАНЕЛЬ",
            now_playing = "СЕЙЧАС ИГРАЕТ",
            now_playing_glob = "СЕЙЧАС ИГРАЕТ (ОБЩЕЕ)",
            now_playing_local = "СЕЙЧАС ИГРАЕТ (ЛОКАЛЬНО)",
            no_song = "Нет трека",
            uploader_system = "СИСТЕМА",
            uploader_you = "ВЫ",
            uploader_prefix = "Загрузил",
            pending_count = "В очереди",
            pending_you = "В вашей очереди",
            live = "ПРЯМОЙ ЭФИР",
            local_songs = "Локальные треки сервера",
            all_files = "Всего файлов",
            search_placeholder = "Поиск трека...",
            no_files = "В папке sound/GSP/ отсутствуют файлы. Вы можете попробовать тестовый набор музыки, указанный в описании мода (GSP Template).",
            btn_play = "▶ ИГРАТЬ",
            btn_queue = "＋ В ОЧЕРЕДЬ",
            tab_control = "УПРАВЛЕНИЕ",
            tab_queue = "ОЧЕРЕДЬ",
            tab_settings = "НАСТРОЙКИ",
            dj_mode = "Серверный режим",
            dj_mode_desc_on = "Управление глобальным состоянием сервера",
            dj_mode_desc_off = "Управление только вашим клиентом",
            vol_global = "Глобальная громкость (Сервер)",
            vol_local = "Ваша громкость (Клиент)",
            btn_pause = "⏸ ПАУЗА",
            btn_resume = "▶ ПРОДОЛЖИТЬ",
            btn_loop_server = "🔁 ПОВТОР СЕРВЕРА",
            btn_loop_client = "🔁 ПОВТОР КЛИЕНТА",
            btn_stop = "СТОП",
            btn_next = "СЛЕДУЮЩИЙ ТРЕК ⏩",
            url_player_title = "Удаленный URL-плеер",
            url_player_placeholder = "Вставьте ссылку и нажмите Enter...",
            queue_pending_title = "Треки в очереди",
            queue_all = "(Для всех)",
            queue_you = "(Только для вас)",
            queue_empty = "Очередь пуста.",
            queue_client_empty = "Ваша локальная очередь пуста.",
            queue_upcoming = "Следующие треки (Локально)",
            local_settings_title = "Локальные настройки (Ваш Клиент)",
            mute_title = "Полное глушение",
            mute_desc = "Полностью заглушает звук аддона на вашем компьютере.",
            lang_title = "Язык интерфейса",
            lang_desc = "Выберите язык интерфейса.",
            personal_settings = "Личные Настройки",
            btn_mute = "🔇 ВЫКЛЮЧИТЬ ЗВУК",
            btn_unmute = "🔊 ВКЛЮЧИТЬ ЗВУК",
            btn_save_default_vol = "💾 СОХРАНИТЬ ГРОМКОСТЬ ПО УМОЛЧАНИЮ",
            footer_dual_engine = "Система GSP: Dual Audio Engine",
            footer_client_mode = "Режим клиента GSP",
            footer_admin_mode = "Режим Админа / Сервера",
            footer_local_mode = "Локальный режим клиента",
            close_key_title = "Клавиша закрытия панели",
            close_key_desc = "Выберите горячую клавишу для закрытия интерфейса.",
            press_any_key = "НАЖМИТЕ ЛЮБУЮ КЛАВИШУ...",
        },
        admin = {
            title = "GSP - ПАНЕЛЬ АДМИНИСТРАТОРА ПРАВ ДОСТУПА",
            close_panel = "✕ ПАНЕЛЬ УПРАВЛЕНИЯ",
            music_ranks_title = "МУЗЫКАЛЬНЫЕ РАНГИ (DJ)",
            music_ranks_desc = "Пользователи с этими рангами имеют доступ к плееру !music и функциям глобального DJ-сервера.",
            admin_ranks_title = "АДМИНИСТРАТИВНЫЕ РАНГИ (MGR)",
            admin_ranks_desc = "Пользователи с этими рангами имеют полный доступ к этой панели и решают, кто является DJ, а кто Администратором прав доступа.",
            input_placeholder = "Имя ранга...",
            btn_add = "ДОБАВИТЬ",
            rank_protected = "Защищено",
            tool_delete = "Удалить ранг",
            footer_engine = "Движок прав GSP: Автономное окно управления",
            footer_area = "Зона безопасности администратора"
        }
    },
    es = {
        player = {
            title_server = "GSP - Gmod Sound Player (Control del Servidor)",
            title_client = "GSP - Gmod Sound Player (Control del Cliente)",
            close_panel = "✕ CERRAR PANEL",
            now_playing = "REPRODUCIENDO",
            now_playing_glob = "REPRODUCIENDO (GLOBAL)",
            now_playing_local = "REPRODUCIENDO (LOCAL)",
            no_song = "Sin canción",
            uploader_system = "SISTEMA",
            uploader_you = "TÚ",
            uploader_prefix = "Subido por",
            pending_count = "Pendientes",
            pending_you = "Pendientes para ti",
            live = "EN VIVO",
            local_songs = "Canciones locales del servidor",
            all_files = "Todos los archivos",
            search_placeholder = "Buscar canción...",
            no_files = "Faltan archivos en sound/GSP/. Puedes probar el paquete de música de prueba incluido en la descripción del mod (GSP Template).",
            btn_play = "▶ REPRODUCIR",
            btn_queue = "＋ COLA",
            tab_control = "CONTROL",
            tab_queue = "COLA",
            tab_settings = "AJUSTES",
            dj_mode = "Modo de Servidor",
            dj_mode_desc_on = "Anular el estado global del servidor",
            dj_mode_desc_off = "Gestionar solo tu cliente local",
            vol_global = "Volumen Global (Servidor)",
            vol_local = "Tu Volumen (Cliente)",
            btn_pause = "⏸ PAUSAR",
            btn_resume = "▶ REANUDAR",
            btn_loop_server = "🔁 REPETIR SERVIDOR",
            btn_loop_client = "🔁 REPETIR CLIENTE",
            btn_stop = "DETENER",
            btn_next = "SIGUIENTE PISTA ⏩",
            url_player_title = "Reproductor de URL remota",
            url_player_placeholder = "Pega el enlace y presiona Enter...",
            queue_pending_title = "Pistas pendientes",
            queue_all = "(Para todos)",
            queue_you = "(Solo para ti)",
            queue_empty = "La cola está vacía.",
            queue_client_empty = "Tu cola local está vacía.",
            queue_upcoming = "Siguientes pistas (Local)",
            local_settings_title = "Ajustes Locales (Tu Cliente)",
            mute_title = "Silencio Total",
            mute_desc = "Silencia completamente el sonido del addon en tu computadora.",
            lang_title = "Idioma de la interfaz",
            lang_desc = "Elige el idioma de la interfaz.",
            personal_settings = "Ajustes Personales",
            btn_mute = "🔇 SILENCIAR ADDON",
            btn_unmute = "🔊 ACTIVAR SONIDO",
            btn_save_default_vol = "💾 GUARDAR VOLUMEN POR DEFECTO",
            footer_dual_engine = "GSP Sistema: Dual Audio Engine",
            footer_client_mode = "GSP Modo Cliente",
            footer_admin_mode = "Modo Admin / Servidor",
            footer_local_mode = "Modo Cliente Local",
            close_key_title = "Tecla de cierre del panel",
            close_key_desc = "Elige la tecla de acceso rápido para cerrar la interfaz.",
            press_any_key = "PRESIONA UNA TECLA...",
        },
        admin = {
            title = "GSP - PANEL DE ADMINISTRACIÓN DE PERMISOS",
            close_panel = "✕ CERRAR PANEL",
            music_ranks_title = "RANGOS DE MÚSICA (DJ)",
            music_ranks_desc = "Los usuarios con estos rangos pueden acceder al reproductor !music y a las funciones globales del servidor DJ.",
            admin_ranks_title = "RANGOS ADMINISTRATIVOS (MGR)",
            admin_ranks_desc = "Los usuarios con estos rangos tienen acceso completo a este panel y deciden quién es DJ y quién es Administrador de permisos.",
            input_placeholder = "Nombre del rango...",
            btn_add = "AÑADIR",
            rank_protected = "Protegido",
            tool_delete = "Eliminar rango",
            footer_engine = "GSP Motor de Permisos: Ventana de gestión autónoma",
            footer_area = "Área de seguridad de administración"
        }
    },
    de = {
        player = {
            title_server = "GSP - Gmod Sound Player (Serversteuerung)",
            title_client = "GSP - Gmod Sound Player (Clientsteuerung)",
            close_panel = "✕ PANEL SCHLIESSEN",
            now_playing = "GERADE WIEDERGEGEBEN",
            now_playing_glob = "GERADE WIEDERGEGEBEN (GLOBAL)",
            now_playing_local = "GERADE WIEDERGEGEBEN (LOKAL)",
            no_song = "Kein Lied",
            uploader_system = "SYSTEM",
            uploader_you = "DU",
            uploader_prefix = "Hochgeladen von",
            pending_count = "Ausstehend",
            pending_you = "Ausstehend für dich",
            live = "LIVE",
            local_songs = "Lokale Server-Lieder",
            all_files = "Alle Dateien",
            search_placeholder = "Lied suchen...",
            no_files = "Im Ordner sound/GSP/ fehlen Dateien. Du kannst das Test-Musikpaket ausprobieren, das in der Mod-Beschreibung enthalten ist (GSP Template).",
            btn_play = "▶ ABSPIELEN",
            btn_queue = "＋ WARTESCHLANGE",
            tab_control = "STEUERUNG",
            tab_queue = "WARTESCHLANGE",
            tab_settings = "EINSTELLUNGEN",
            dj_mode = "Servermodus",
            dj_mode_desc_on = "Überschreiben des globalen Serverstatus",
            dj_mode_desc_off = "Nur Ihren lokalen Client verwalten",
            vol_global = "Globale Lautstärke (Server)",
            vol_local = "Ihre Lautstärke (Client)",
            btn_pause = "⏸ PAUSE",
            btn_resume = "▶ FORTSETZEN",
            btn_loop_server = "🔁 SERVER WIEDERHOLEN",
            btn_loop_client = "🔁 CLIENT WIEDERHOLEN",
            btn_stop = "STOPP",
            btn_next = "NÄCHSTER TITEL ⏩",
            url_player_title = "Remote-URL-Player",
            url_player_placeholder = "Link einfügen und Eingabetaste drücken...",
            queue_pending_title = "Ausstehende Titel",
            queue_all = "(Mit allen)",
            queue_you = "(Nur für dich)",
            queue_empty = "Warteschlange ist leer.",
            queue_client_empty = "Ihre lokale Warteschlange ist leer.",
            queue_upcoming = "Kommende Titel (Lokal)",
            local_settings_title = "Lokale Einstellungen (Ihr Client)",
            mute_title = "Stummschaltung",
            mute_desc = "Schaltet den Ton des Addons auf Ihrem Computer vollständig stumm.",
            lang_title = "Schnittstellensprache",
            lang_desc = "Wählen Sie die Schnittstellensprache.",
            personal_settings = "Persönliche Einstellungen",
            btn_mute = "🔇 ADDON STUMMSCHALTEN",
            btn_unmute = "🔊 TON EINSCHALTEN",
            btn_save_default_vol = "💾 LAUTSTÄRKE ALS STANDARD SPEICHERN",
            footer_dual_engine = "GSP-System: Dual Audio Engine",
            footer_client_mode = "GSP-Client-Modus",
            footer_admin_mode = "Admin- / Servermodus",
            footer_local_mode = "Lokaler Client-Modus",
            close_key_title = "Taste zum Schließen des Panels",
            close_key_desc = "Wählen Sie die Tastenkombination zum Schließen der Benutzeroberfläche.",
            press_any_key = "TASTE DRÜCKEN...",
        },
        admin = {
            title = "GSP - RECHTE-ADMINISTRATORPANEL",
            close_panel = "✕ PANEL SCHLIESSEN",
            music_ranks_title = "MUSIK-RÄNGE (DJ)",
            music_ranks_desc = "Benutzer mit diesen Rängen können auf den !music-Player und globale DJ-Serverfunktionen zugreifen.",
            admin_ranks_title = "ADMINISTRATIVE RÄNGE (MGR)",
            admin_ranks_desc = "Benutzer mit diesen Rängen haben vollen Zugriff auf dieses Panel und entscheiden, wer DJ und wer Rechte-Administrator ist.",
            input_placeholder = "Rangname...",
            btn_add = "HINZUFÜGEN",
            rank_protected = "Geschützt",
            tool_delete = "Rang löschen",
            footer_engine = "GSP Rechte-Engine: Eigenständiges Verwaltungsfenster",
            footer_area = "Admin-Sicherheitsbereich"
        }
    }
}